{
    "name": "CS Prefab Configurator",
    "summary": "Prefab configurator met catalogusbeheer, CRM, verkoopofferte en project",
    "version": "saas~19.4.2.16.0",
    "category": "Website",
    "license": "LGPL-3",
    "author": "Codesnap",
    "depends": ["website", "crm", "sale_management", "sale_crm", "sale_project", "sale_purchase_project"],
    "data": [
        "security/ir.access.csv",
        "data/native_sales.xml",
        "views/quote_views.xml",
        "views/catalog_views.xml",
        "views/native_sales_views.xml",
        "views/appearance_views.xml",
        "views/project_workflow_views.xml",
        "views/purchase_workflow_views.xml",
        "report/quote_report.xml",
        "data/cron.xml",
    ],
    "installable": True,
    "application": True,
}
